Add report

diff --git a/.github/workflows/report.yml b/.github/workflows/report.yml
--- a/.github/workflows/report.yml
+++ b/.github/workflows/report.yml
@@ -39,17 +39,12 @@ jobs:
             sudo mv allure-history/${{ github.run_number }}/* allure-history/${{ github.run_number }}/allure-report/ || echo "Failed to copy Allure files to managed directory"
             echo "Allure files copied to managed directory"
             sudo ls allure-history/${{ github.run_number }}/allure-report
+            sudo mkdir allure-history/${{ github.run_number }}/swagger-coverage-report
+            sudo cp allure-results/swagger-coverage-report.html allure-history/${{ github.run_number }}/swagger-coverage-report/index.html || echo "Failed to copy swagger report"
+            sudo ls allure-history/${{ github.run_number }}/swagger-coverage-report
           else
             echo "No Allure files found to copy"
           fi
-
-      - name: Copy Swagger coverage report
-        run: |
-          if [ -f allure-results/swagger-coverage-report.html ]; then
-            sudo mkdir allure-history/${{ github.run_number }}/swagger-coverage-report
-            sudo cp allure-results/swagger-coverage-report.html allure-history/${{ github.run_number }}/swagger-coverage-report/index.html || echo "Failed to copy swagger report"
-          fi
-          sudo ls allure-history/${{ github.run_number }}/swagger-coverage-report
 
       - name: Extract metrics and generate dashboard
         run: |
