Add report

diff --git a/.github/workflows/report.yml b/.github/workflows/report.yml
--- a/.github/workflows/report.yml
+++ b/.github/workflows/report.yml
@@ -53,10 +53,10 @@ jobs:
       - name: Copy Swagger coverage report
         run: |
           if [ -f allure-results/swagger-coverage-report.html ]; then
-            sudo mkdir allure-history/${{ github.run_number }}/swagger-coverage-report
-            sudo cp allure-results/swagger-coverage-report.html allure-history/${{ github.run_number }}/swagger-coverage-report/index.html || echo "Failed to copy swagger report"
+            sudo mkdir gh-pages/w1/${{ github.run_number }}/swagger-coverage-report
+            sudo cp allure-results/swagger-coverage-report.html gh-pages/w1/${{ github.run_number }}/swagger-coverage-report/index.html || echo "Failed to copy swagger report"
           fi
-          sudo ls allure-history/${{ github.run_number }}/swagger-coverage-report
+          sudo ls gh-pages/w1/${{ github.run_number }}/swagger-coverage-report
 
       - name: Extract metrics and generate dashboard
         run: |
@@ -69,7 +69,7 @@ jobs:
           fi
           # Execute extract-metrics.sh script
           chmod +x .github/scripts/extract-metrics.sh
-          .github/scripts/extract-metrics.sh allure-history/${{ github.run_number }}/ allure-history/${{ github.run_number }}/ allure-history/${{ github.run_number }}
+          .github/scripts/extract-metrics.sh allure-history/${{ github.run_number }}/allure-report/ gh-pages/w1/${{ github.run_number }}/swagger-coverage-report/ allure-history/${{ github.run_number }}
           echo "Metrics extracted and dashboard generated"
 
       - name: Publish test report
