Add report

diff --git a/.github/workflows/report.yml b/.github/workflows/report.yml
--- a/.github/workflows/report.yml
+++ b/.github/workflows/report.yml
@@ -49,7 +49,7 @@ jobs:
       - name: Copy Allure report to managed directory
         run: |
           sudo ls -R allure-history
-          if [ -f allure-history/index.html ]; then
+          if [ -f allure-history/${{ github.run_number }}/index.html ]; then
             sudo cp allure-history/${{ github.run_number }}/index.html allure-history/${{ github.run_number }}/allure-report.html || echo "Failed to copy Allure report to managed directory"
             echo "Allure report copied to managed directory"
             cat allure-history/${{ github.run_number }}/allure-report.html
@@ -62,6 +62,9 @@ jobs:
           # Copy logo to allure-history directory
           if [ -f .github/report/logo_icon.png ]; then
             sudo cp .github/report/logo_icon.png allure-history/${{ github.run_number }}/ || echo "Failed to copy logo"
+          fi
+          if [ -f .github/report/report_styles.css ]; then
+            sudo cp .github/report/report_styles.css allure-history/${{ github.run_number }}/ || echo "Failed to styles"
           fi
           # Execute extract-metrics.sh script
           chmod +x .github/scripts/extract-metrics.sh
